version: '3'
services:
  backend:
    image: my-springboot-app
    build:
      context: ./prototype1  # Path to your Spring Boot app directory
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /tmp
    networks:
      - app-network

  frontend:
    image: my-angular-app
    build:
      context: ./prototype-front/angular-pantry-prototype  
      dockerfile: Dockerfile
    ports:
      - "4200:4200" 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
