version: 2.1

jobs:
  build_frontend:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Angular dependencies
          command: npm install
      - run:
          name: Build Angular app
          command: npm run build -- --prod
      - run:
          name: Build and tag frontend Docker image
          command: |
            docker build -t calvinjohnson747/pantryangularapp:latest .
      - run:
          name: Push frontend Docker image to Docker Hub
          command: |
            echo "Cjjjjj123#" | docker login -u "calvinjohnson747" --password-stdin
            docker push calvinjohnson747/pantryangularapp:latest

  build_backend:
    docker:
      - image: circleci/openjdk:17
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build Spring Boot application
          command: mvn clean package -DskipTests
      - run:
          name: Build and tag backend Docker image
          command: |
            docker build -t calvinjohnson747/pantryspringapp:latest .
      - run:
          name: Push backend Docker image to Docker Hub
          command: |
            echo "Cjjjjj123#" | docker login -u "calvinjohnson747" --password-stdin
            docker push calvinjohnson747/pantryspringapp:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_frontend
      - build_backend
